import argparse
import pandas as pd
import anndata as ad
from pathlib import Path

parser = argparse.ArgumentParser(prog='h5ad_extract', description='Get the X values and proportions from a h5ad file generated from scaden simulate.')
parser.add_argument('h5ad_file', help='h5ad file generated by scaden simulate')
parser.add_argument('out_dir', help='Directory to save proportions and data')
parser.add_argument('-p', '--prefix', default='test', help="Names of the output files (e.g., -p test will create the files 'test_proportions.tsv' and 'test_data.tsv')")
args = parser.parse_args()

h5ad_file = Path(args.h5ad_file)
out_dir = Path(args.out_dir)

if not h5ad_file.is_file():
    raise OSError(f"h5ad_file '{args.h5ad_file}' cannot be found.")
if not out_dir.is_dir():
    raise OSError(f"Directory '{args.out_dir}' cannot be found.")

out_prop = out_dir/f'{args.prefix}_proportions.tsv'
out_data = out_dir/f'{args.prefix}_data.tsv'
    
adata = ad.read_h5ad(h5ad_file)

# Testing set proportions
g = adata.obs.drop(columns='ds')
g.index = 'sample' + g.index
g.to_csv(out_prop, sep='\t')
print(f'Saved test set proportions to {out_prop}')

# Testing set X values
testdata = adata.to_df().copy().transpose()
testdata.columns = 'sample' + testdata.columns
testdata.to_csv(out_data, sep='\t')
print(f'Saved test set data to {out_data}')
